version: '3.9'
services:
  backend:
    build: ./backend
    container_name: nest-backend
    command: npm run start:dev
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=meubanco
      - PORT=3001
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: next-frontend
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
